# Generated by Django 5.1.6 on 2025-02-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentarios",
            old_name="cometario",
            new_name="comentario",
        ),
        migrations.AlterField(
            model_name="comentarios",
            name="data_publicacao",
            field=models.DateField(default=""),
        ),
    ]
