# Generated by Django 5.1.6 on 2025-02-19 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0002_rename_cometario_comentarios_comentario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comentarios",
            name="data_publicacao",
        ),
        migrations.AddField(
            model_name="comentarios",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comentarios",
            name="comentario",
            field=models.CharField(default="", max_length=250),
        ),
    ]
