# Generated by Django 5.1.6 on 2025-02-19 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0004_alter_comentarios_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentarios",
            name="data_publicacao",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 19, 23, 58, 3, 383654, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
